common: don't pass --manifest-branch if revision is None
This fixes the following unit test with gitrepo 2.31.1:

======================================================================
ERROR: test_branch_defaults_to_HEAD (repo_resource.test_check.TestCheck.test_branch_defaults_to_HEAD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/repo_resource/test_check.py", line 92, in test_branch_defaults_to_HEAD
    check.check(instream)
  File "/root/repo_resource/check.py", line 45, in check
    raise e
  File "/root/repo_resource/check.py", line 41, in check
    repo.init(config.url, config.revision, config.name, config.depth)
  File "/root/repo_resource/common.py", line 167, in init
    raise (e)
  File "/root/repo_resource/common.py", line 163, in init
    repo._Main(repo_cmd)
  File "/usr/local/lib/python3.11/site-packages/repo/main.py", line 666, in _Main
    result = repo._Run(name, gopts, argv) or 0
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/repo/main.py", line 222, in _Run
    with Trace('starting new command: %s', ', '.join([name] + argv),
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 5: expected str instance, NoneType found

----------------------------------------------------------------------

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>